# Generated by Django 5.2.1 on 2025-06-09 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_caritem_historyitem_package_signgroup_theorygroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textP', models.TextField(verbose_name='Текст вопроса')),
                ('imageP', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textR', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correctR', models.BooleanField(default=False, verbose_name='Правильный?')),
                ('questionR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.questionr')),
            ],
        ),
    ]
