# Generated by Django 5.2.1 on 2025-06-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_questionr_answerr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerR',
        ),
        migrations.DeleteModel(
            name='QuestionR',
        ),
    ]
