# Generated by Django 5.2.1 on 2025-07-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_answerr_delete_questionr'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
