# Generated by Django 5.2.1 on 2025-07-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_test_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='order',
        ),
    ]
